#!/bin/bash

# Variables
NETID=dxy170002
MACHINE0=cs1
MACHINE1=net01
MACHINE2=net02
MACHINE3=net03
MACHINE4=net04
DOMAIN=utdallas.edu
SOURCE_EXECUTABLE=bin/main
TARGET_EXECUTABLE=project2

# Copy Executable to Home Directory
scp $SOURCE_EXECUTABLE $NETID@$MACHINE0.$DOMAIN:~/$TARGET_EXECUTABLE
#scp $SOURCE_EXECUTABLE $NETID@$MACHINE1.$DOMAIN:~/$TARGET_EXECUTABLE
#scp $SOURCE_EXECUTABLE $NETID@$MACHINE2.$DOMAIN:~/$TARGET_EXECUTABLE
#scp $SOURCE_EXECUTABLE $NETID@$MACHINE3.$DOMAIN:~/$TARGET_EXECUTABLE
#scp $SOURCE_EXECUTABLE $NETID@$MACHINE4.$DOMAIN:~/$TARGET_EXECUTABLE

# Launch SSH Sessions
bash -c "ssh -t $NETID@$MACHINE1.$DOMAIN "./$TARGET_EXECUTABLE 0""